---

stages:
  - test
  - build
  - release

## Disable until initial format/lint get applied

variables:

  DOCKER_REGISTRY: 'artifactory.pdsea.f5net.com'
  JOURNEYS_DOCKER_BASE: f5-cxt-docker/journeys
  JOURNEYS_TAG: $CI_COMMIT_REF_NAME


format-and-lint:
  stage: test
  image: python:3.8
  tags:
    - docker-executor
  script:
    - pip install -r requirements.txt -r test-requirements.txt
    - make format
    - git diff --exit-code
    - make lint

test:
  stage: test
  image: python:3.8
  tags:
    - docker-executor
  script:
    - pip install -r requirements.txt -r test-requirements.txt
    - make test

build:
  stage: build
  image: docker
  tags:
    - docker-executor
  script:
    - 'echo "__build_ref__ = \""${CI_BUILD_REF}"\"" >> journeys/__init__.py'
    - docker login -u="${DOCKER_USER}" -p="${DOCKER_TOKEN}" ${DOCKER_REGISTRY}
    - docker build -t ${DOCKER_REGISTRY}/${JOURNEYS_DOCKER_BASE}:${JOURNEYS_TAG} .
    - docker tag ${DOCKER_REGISTRY}/${JOURNEYS_DOCKER_BASE}:${JOURNEYS_TAG} ${DOCKER_REGISTRY}/${JOURNEYS_DOCKER_BASE}:latest
    - docker tag ${DOCKER_REGISTRY}/${JOURNEYS_DOCKER_BASE}:${JOURNEYS_TAG} ${DOCKER_REGISTRY}/${JOURNEYS_DOCKER_BASE}:${CI_COMMIT_SHORT_SHA}
    - docker push ${DOCKER_REGISTRY}/${JOURNEYS_DOCKER_BASE}:${JOURNEYS_TAG}
    - docker push ${DOCKER_REGISTRY}/${JOURNEYS_DOCKER_BASE}:latest
    - docker push ${DOCKER_REGISTRY}/${JOURNEYS_DOCKER_BASE}:${CI_COMMIT_SHORT_SHA}

  only:
    - master
  retry:
    max: 2

pages:
  image: node
  stage: build
  tags:
    - docker-executor
  script:
    - npm install @openapitools/openapi-generator-cli -g
    - apt update
    - apt install -y default-jre
    - npx @openapitools/openapi-generator-cli generate -i journeys/backend/api-schema.yaml -g html -o public
  artifacts:
    paths:
    - public
  only:
  - master

release:
  stage: release
  image: docker
  tags:
    - docker-executor
  script:
    - export RELEASE_TAG=`echo $CI_BUILD_REF_NAME | sed 's/v//g'`
    - export RELEASE_CONTAINER=latest
    - docker login -u="${DOCKER_USER}" -p="${DOCKER_TOKEN}" ${DOCKER_REGISTRY}
    - docker pull ${DOCKER_REGISTRY}/${JOURNEYS_DOCKER_BASE}:${RELEASE_CONTAINER}
    - docker tag ${DOCKER_REGISTRY}/${JOURNEYS_DOCKER_BASE}:${RELEASE_CONTAINER} ${DOCKER_REGISTRY}/${JOURNEYS_DOCKER_BASE}:${RELEASE_TAG}
    - docker push ${DOCKER_REGISTRY}/${JOURNEYS_DOCKER_BASE}:${RELEASE_TAG}
  dependencies:
    - build
  only:
    - /^v\d{1,}\.\d{1,}.*/i # v1.1 or v1.2beta etc
  retry:
    max: 2
