NONAME = {
    ("auth", "password-policy"),
    ("auth", "remote-role"),
    ("auth", "remote-user"),
    ("auth", "source"),
    ("cli", "admin-partitions"),
    ("cli", "global-settings"),
    ("cli", "preference"),
    ("ltm", "default-node-monitor"),
    ("ltm", "dns", "analytics", "global-settings"),
    ("ltm", "dns", "cache", "global-settings"),
    ("net", "cos global-settings"),
    ("net", "lldp-globals"),
    ("net", "packet-filter-trusted"),
    ("net", "stp-globals"),
    ("sys", "datastor"),
    ("sys", "dns"),
    ("sys", "global-settings"),
    ("sys", "httpd"),
    ("sys", "log-rotate"),
    ("sys", "ntp"),
    ("sys", "outbound-smtp"),
    ("sys", "scriptd"),
    ("sys", "snmp"),
    ("sys", "software", "update"),
    ("sys", "sshd"),
    ("sys", "state-mirroring"),
    ("wom", "endpoint-discovery"),
}
BLOBTYPES = {
    ("cli", "script"),
    ("ltm", "rule"),
    ("gtm", "rule"),
    ("sys", "application", "apl-script"),
    ("sys", "application", "template"),
    ("sys", "icall", "script"),
}
LISTTYPES = {
    "analytics gui-widget": ("drilldown-entities", "drilldown-values", "metrics"),
    "analytics predefined-report": ("values",),
    "apm profile access": ("accept-languages",),
    "cm device": ("active-modules", "optional-modules"),
    "cm trust-domain": ("ca-devices",),
    "ltm policy": ("controls", "requires", "values"),
    "ltm profile client-ssl": ("cert-extension-includes", "options"),
    "ltm profile server-ssl": ("c3d-cert-extension-includes", "options"),
    "ltm profile http-compression": (
        "content-type-include",
        "content-type-exclude",
        "uri-include",
        "uri-exclude",
    ),
    "sys dns": ("name-servers",),
    "sys management-dhcp": ("request-options",),
    "sys ntp": ("servers",),
    "sys snmp": ("agent-addresses", "allowed-addresses"),
}
MODULES = (
    "analytics",
    "apm",
    "asm",
    "auth",
    "cli",
    "gtm",
    "ilx",
    "ltm",
    "net",
    "pem",
    "security",
    "sys",
    "vcmp",
    "wam",
    "wom",
)
